output_header = ['url', 'meta_name', 'text', 'x_coords', 'y_coords', 'block_height', 'block_width', 'tag', 'num_child',
          'num_siblings']

css_header = ['border-top-width', 'table-layout', '-webkit-shape-margin', '-webkit-flow-into',
          '-webkit-animation-iteration-count', 'min-height', '-webkit-region-fragment', '-webkit-highlight',
          '-webkit-column-rule-width', '-webkit-rtl-ordering', 'background-size', 'font-size', 'text-shadow',
          '-webkit-user-drag', '-webkit-box-flex', 'clear', '-webkit-mask-box-image-width', 'color',
                 '-webkit-border-vertical-spacing', '-webkit-background-composite', 'background-origin', 'outline-offset',
                 'list-style-type', '-webkit-font-kerning', 'padding-bottom', 'left', '-webkit-perspective-origin',
                 'text-overflow', 'display', 'border-left-style', 'clip-rule', 'unicode-bidi', 'stop-opacity',
                 'border-image-outset', '-webkit-hyphens', '-webkit-transition-timing-function', '-webkit-box-pack',
                 '-webkit-perspective', 'outline-style', '-webkit-backface-visibility', 'resize',
                 '-webkit-mask-box-image-slice', 'clip-path', 'overflow-x', '-webkit-column-width', '-webkit-column-gap',
                 '-webkit-text-security', '-webkit-flex-direction', '-webkit-text-decorations-in-effect',
                 '-webkit-shape-inside', '-webkit-animation-duration', '-webkit-line-grid', 'margin-top', 'flood-color',
                 '-webkit-mask-repeat', 'box-sizing', 'shape-rendering', 'overflow-wrap', 'color-interpolation-filters',
                 'overflow-y', 'border-left-color', 'word-wrap', '-webkit-transform-origin', '-webkit-grid-definition-rows',
                 '-webkit-flex-shrink', '-webkit-color-correction', '-webkit-background-origin', 'top', 'padding-top',
                 'outline-width', '-webkit-mask-image', 'border-image-width', 'stroke-miterlimit', 'border-bottom-color',
                 'dominant-baseline', 'transition-property', '-webkit-margin-before-collapse',
                 '-webkit-hyphenate-limit-before', '-webkit-column-span', '-webkit-tap-highlight-color', 'font-weight',
                 'border-left-width', 'writing-mode', 'padding-right', '-webkit-shape-outside', '-webkit-mask-box-image',
                 '-webkit-background-blend-mode', 'color-rendering', '-webkit-svg-shadow', '-webkit-text-emphasis-position',
                 '-webkit-background-size', 'kerning', '-webkit-flow-from', '-webkit-border-image', 'baseline-shift',
                 '-webkit-line-align', '-webkit-grid-definition-columns', 'margin-bottom', '-webkit-flex-basis',
                 'background-attachment', 'glyph-orientation-horizontal', '-webkit-box-shadow', '-webkit-box-align',
                 '-webkit-transform', 'box-shadow', 'z-index', 'stop-color', 'border-top-style', '-webkit-flex-grow',
                 'background-repeat', '-webkit-wrap-flow', 'orphans', '-webkit-box-orient', 'letter-spacing',
                 '-webkit-mask-clip', '-webkit-animation-play-state', '-webkit-nbsp-mode', 'border-top-left-radius',
                 '-webkit-filter', 'background-position', '-webkit-border-horizontal-spacing', '-webkit-column-progression',
                 'stroke-linecap', '-webkit-border-fit', 'background-image', '-webkit-box-reflect', 'widows',
                 '-webkit-user-modify', 'stroke-dasharray', 'text-rendering', '-webkit-grid-before',
                 '-webkit-grid-auto-columns', 'border-image-slice', '-webkit-background-clip', 'stroke', 'border-image-repeat',
                 '-webkit-flex-wrap', '-webkit-box-ordinal-group', 'text-transform', 'outline-color', 'list-style-position',
                 'glyph-orientation-vertical', 'padding-left', 'stroke-linejoin', '-webkit-column-break-inside', 'right',
                 'fill-rule', '-webkit-user-select', 'min-width', '-webkit-mask-size', '-webkit-order', 'zoom',
                 '-webkit-column-count', '-webkit-marquee-direction', 'max-width', '-webkit-transition-duration',
                 'border-right-color', 'cursor', 'opacity', '-webkit-marquee-style', '-webkit-margin-after-collapse',
                 '-webkit-grid-auto-flow', 'color-interpolation', 'direction', 'background-clip', 'border-bottom-width',
                 'page-break-after', 'border-image-source', '-webkit-blend-mode', 'stroke-opacity', 'font-style',
                 '-webkit-mask-composite', '-webkit-text-stroke-width', '-webkit-locale', 'fill-opacity',
                 '-webkit-writing-mode', 'font-family', '-webkit-shape-padding', 'stroke-dashoffset', 'float',
                 '-webkit-column-rule-style', 'width', 'margin-right', '-webkit-hyphenate-limit-after', 'alignment-baseline',
                 'text-indent', 'vector-effect', 'marker-mid', '-webkit-marquee-increment', '-webkit-column-rule-color',
                 'margin-left', '-webkit-column-break-before', '-webkit-transition-property', '-webkit-mask-box-image-repeat',
                 'border-right-style', '-webkit-align-content', '-webkit-transition-delay', '-webkit-mask-box-image-outset',
                 'image-rendering', 'border-bottom-left-radius', '-webkit-line-box-contain', '-webkit-animation-delay',
                 '-webkit-marquee-repetition', 'border-top-color', '-webkit-box-flex-group', '-webkit-text-orientation',
                 '-webkit-hyphenate-character', 'speak', '-webkit-hyphenate-limit-lines', 'text-anchor',
                 '-webkit-wrap-through', '-webkit-box-decoration-break', '-webkit-text-stroke-color', 'tab-size',
                 'background-color', 'height', 'vertical-align', '-webkit-line-snap', 'border-bottom-style',
                 '-webkit-animation-direction', 'caption-side', 'transition-duration', '-webkit-grid-end', 'marker-end',
                 'line-height', 'filter', 'text-decoration', 'visibility', '-webkit-grid-after', '-webkit-align-self',
                 '-webkit-appearance', '-webkit-box-direction', 'pointer-events', '-webkit-region-break-inside',
                 'marker-start', 'word-break', '-webkit-animation-timing-function', '-webkit-region-break-before',
                 'border-bottom-right-radius', 'mask-type', 'list-style-image', '-webkit-mask-box-image-source',
                 'transition-timing-function', '-webkit-justify-content', '-webkit-column-axis', '-webkit-text-emphasis-color',
                 'bottom', '-webkit-transform-style', 'border-collapse', '-webkit-font-smoothing',
                 '-webkit-text-emphasis-style', '-webkit-mask-origin', '-webkit-line-clamp', '-webkit-mask-position',
                 'text-align', '-webkit-grid-start', '-webkit-region-break-after', 'fill', 'page-break-before',
                 '-webkit-animation-fill-mode', '-webkit-column-break-after', 'font-variant', 'clip',
                 'border-top-right-radius', '-webkit-print-color-adjust', 'empty-cells', 'word-spacing', '-webkit-line-break',
                 'lighting-color', '-webkit-text-fill-color', 'transition-delay', 'border-right-width', 'position',
                 'flood-opacity', '-webkit-text-combine', '-webkit-font-variant-ligatures', 'mask', 'white-space',
                 '-webkit-box-lines', '-webkit-animation-name', '-webkit-align-items', 'page-break-inside',
                 '-webkit-grid-auto-rows', '-webkit-clip-path', 'max-height', 'stroke-width', 'buffered-rendering']
